language: generic

services:
  - docker

before_install:
  - docker build -t ari/dockedship -f Dockerfile.dev .

script:
  - docker run -e CI=true ari/dockedship npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockedship"
  env: "Dockedship-env"
  bucket_name: "elasticbeanstalk-us-east-2-744189490109"
  bucket_path: "dockedship"
  on:
    branch: master
  access_key_id: "$aws_access_key"
  secret_access_key: "$aws_secret_key"
